spring.application.name=api-implementation
spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.datasource.username=sa
#spring.datasource.password=
spring.h2.console.path=/h2-console
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jackson.mapper.sort-properties-alphabetically=false
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.shutdown.access=unrestricted
server.shutdown=graceful
management.info.env.enabled=true
info.app.name=MyNewApp
info.app.description=MyNewApp
info.app.version=1.0

spring.datasource.url=jdbc:postgresql://localhost:5432/api_implementation
spring.datasource.username=venkata
spring.datasource.password=venkata

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect