spring:
  application:
    name: configdemo
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  output:
    ansi:
      enabled: ALWAYS

build:
    id: ${id}
    version: ${version}
    name: ${name}

logging:
  level:
    root: INFO
  file:
    name: ${CONFIGDEMO_LOG_FILE:logs/configdemo.log}

