spring:
  application:
    name: configdemo
  profiles:
    active:
      - prod

  config:
    import: configserver:http://localhost:8888

build:
    id: ${id}
    version: ${version}
    name: ${name}




