spring.application.name=user-service
server.port=${SERVER_PORT:8081}

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

spring.datasource.url=${USER_DB_URL:jdbc:h2:file:./data/userdb;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${USER_DB_USERNAME:sa}
spring.datasource.password=${USER_DB_PASSWORD:}
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=${H2_CONSOLE_ENABLED:true}
spring.h2.console.path=/h2-console
spring.cloud.config.import-check.enabled=false
eureka.client.enabled=true
eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


logging.level.root=INFO
logging.file.name=${USER_SERVICE_LOG_FILE:logs/user-service.log}
