spring.application.name=user-service
server.port=${SERVER_PORT:8081}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.mongodb.uri=
spring.mongodb.database=userdb
spring.data.mongodb.gridfs.database=userdb
