server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ramkrishna88/api-implementation.git
          search-paths: config-mgmt
          default-label: main
