spring.application.name=product-service
server.port=${SERVER_PORT:8082}

spring.datasource.url=jdbc:mysql://localhost:3306/product_db
spring.datasource.username=venkata
spring.datasource.password=venkata
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
