spring.application.name=cart-service
server.port=${SERVER_PORT:8084}

spring.datasource.url=jdbc:postgresql://localhost:5432/cart_db
spring.datasource.username=venkata
spring.datasource.password=venkata
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

user.service.url=${USER_SERVICE_URL:http://localhost:8081}
product.service.url=${PRODUCT_SERVICE_URL:http://localhost:8082}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
